USE CONCURENCY_ISSUES;

CREATE TABLE Phantom_Reads (
	id INT PRIMARY KEY,
	field INT
);

INSERT INTO Phantom_Reads (id, field) VALUES
(1, 1),
(2, 69);

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM Phantom_Reads;

DROP TABLE Phantom_Reads;