SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
USE CONCURENCY_ISSUES;

BEGIN TRANSACTION;
 
SELECT COUNT(*) FROM Phantom_Reads
WHERE Field = 69;
 
WAITFOR DELAY '00:00:05.000';

SELECT COUNT(*) FROM Phantom_Reads
WHERE Field = 69;
 
COMMIT;