USE CONCURENCY_ISSUES;

CREATE TABLE Dirty_Read (
	id INT PRIMARY KEY,
	field INT
);

INSERT INTO Dirty_Read (id, field) VALUES
(1, 1),
(2, 69);

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM Dirty_Read;

DROP TABLE Dirty_Read;