SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
USE CONCURENCY_ISSUES;

SELECT * FROM Dirty_Read;

BEGIN TRANSACTION;
 
WAITFOR DELAY '00:00:05.000';

SELECT * FROM Dirty_Read;

WAITFOR DELAY '00:00:05.000';
 
COMMIT;