spring:
  application:
    name: computer_store-be
  datasource:
    url: jdbc:postgresql://localhost:5432/computer_store
    username: postgres
    password: bogdan123
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8060
