version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - C:\Uni\Database Management Systems\DBMS_Project_final\java_back_end\init.sql:/docker-entrypoint-initdb.d/init.sql

  spring-app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
