USE CONCURENCY_ISSUES;

CREATE TABLE Dirty_Write (
	id INT PRIMARY KEY,
	field INT
);

INSERT INTO Dirty_Write (id, field) VALUES
(1, 1),
(2, 69);

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM Dirty_Write;

DROP TABLE Dirty_Write;