USE CONCURENCY_ISSUES;

CREATE TABLE Lost_Update (
	id INT PRIMARY KEY,
	field INT
);

INSERT INTO Lost_Update (id, field) VALUES
(1, 1),
(2, 69);

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM Lost_Update;

DROP TABLE Lost_Update;