SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
USE CONCURENCY_ISSUES;

SELECT * FROM Lost_Update;

BEGIN TRANSACTION;
 
UPDATE Lost_Update
SET Field = Field + 420
WHERE Field = 69;
 
SELECT * FROM Lost_Update;
 
WAITFOR DELAY '00:00:05.000';
 
COMMIT;
 
SELECT * FROM Lost_Update;